spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bet7
spring.datasource.username=sa
spring.datasource.password=SuaSenha
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
server.port=8080